#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethods */

#ifndef _Included_NativeMethods
#define _Included_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     NativeMethods
	 * Method:    createUser
	 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_NativeMethods_createUser
		(JNIEnv* , jobject , jstring , jstring , jstring , jstring ,
		jstring , jstring , jstring , jstring , jstring , jstring , jstring ,
		jstring , jstring , jstring , jstring , jstring , jstring );

	/*
	 * Class:     NativeMethods
	 * Method:    modifyUser
	 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_NativeMethods_modifyUser
	(JNIEnv*, jobject, jstring, jstring, jstring);

	/*
	 * Class:     NativeMethods
	 * Method:    deleteUser
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_NativeMethods_deleteUser
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     NativeMethods
	 * Method:    resetPassword
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_NativeMethods_resetPassword
	(JNIEnv*, jobject, jstring, jstring);

	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_ListAllUserFromADs
	(JNIEnv* , jobject);

	JNIEXPORT jlong JNICALL Java_NativeMethods_passWordLastSet
	(JNIEnv* , jobject , jstring );
	JNIEXPORT jlong JNICALL Java_NativeMethods_accountExpires
	(JNIEnv* , jobject , jstring );
	JNIEXPORT jbyteArray JNICALL Java_NativeMethods_profilePic
	(JNIEnv*, jobject, jstring);
	// View account details 
	// General tab;
	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_userGeneralDetails
	(JNIEnv* , jobject , jstring );
	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_userAddresDetails
	(JNIEnv* , jobject , jstring );
	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_userAccountDetails
	(JNIEnv* env, jobject obj, jstring user);
	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_telephone
	(JNIEnv* , jobject , jstring );
	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_organizationDetails
	(JNIEnv* , jobject , jstring );
	JNIEXPORT jbyteArray JNICALL Java_NativeMethods_LoginHours
	(JNIEnv*, jobject ,jstring);
	JNIEXPORT jobjectArray JNICALL Java_NativeMethods_directReports
	(JNIEnv*, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
